import Button from '@mui/material/Button';
import ButtonGroup from '@mui/material/ButtonGroup';
import Link from 'next/link';
import url from '../utility/url';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { grey } from '@mui/material/colors';
export default function Header() {
    const theme = createTheme({
        palette: {
            primary: {
                main: grey[900],
            },
        },
    });
    return (
        <>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <ThemeProvider theme={theme}>
                <ButtonGroup variant="text" aria-label="text button group" fullWidth={true} size="large">
                    {url.map((e) => (
                        <Link href={e.link} key={e.title}>
                            <Button>{e.title}</Button>
                        </Link>
                    ))}
                </ButtonGroup>
            </ThemeProvider>
        </>
    );
}

