import Button from '@mui/material/Button';
import ButtonGroup from '@mui/material/ButtonGroup';
import Link from 'next/link';
import url from '../utility/url';
import Container from '@mui/material/Container';
export default function Header() {

    return (
        <>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <ButtonGroup size="medium" aria-label="large button group" fullWidth={true}>
                {url.map((e) => (
                    <Link href={e.link} key={e.title}>
                        <Button>{e.title}</Button>
                    </Link>
                ))}
            </ButtonGroup>
        </>
    );
}

